USE [master]
GO

/****** Object:  Database [carpinteria]    Script Date: 26/8/2022 11:38:55 ******/
CREATE DATABASE [carpinteria]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'carpinteria', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\carpinteria.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'carpinteria_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\carpinteria_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [carpinteria].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [carpinteria] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [carpinteria] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [carpinteria] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [carpinteria] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [carpinteria] SET ARITHABORT OFF 
GO

ALTER DATABASE [carpinteria] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [carpinteria] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [carpinteria] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [carpinteria] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [carpinteria] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [carpinteria] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [carpinteria] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [carpinteria] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [carpinteria] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [carpinteria] SET  ENABLE_BROKER 
GO

ALTER DATABASE [carpinteria] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [carpinteria] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [carpinteria] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [carpinteria] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [carpinteria] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [carpinteria] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [carpinteria] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [carpinteria] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [carpinteria] SET  MULTI_USER 
GO

ALTER DATABASE [carpinteria] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [carpinteria] SET DB_CHAINING OFF 
GO

ALTER DATABASE [carpinteria] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [carpinteria] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [carpinteria] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [carpinteria] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [carpinteria] SET QUERY_STORE = OFF
GO

ALTER DATABASE [carpinteria] SET  READ_WRITE 
GO


